#!/bin/sh
echo "Running pre-commit hook"
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
if [ -z "$FILES" ];
then
    echo "No files to apply changes to."
    exit 1
fi

# Prettify all selected files
echo "$FILES" | prettier --ignore-unknown --write

echo "Files formatted successfully"

yarn lint --fix

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

echo "Pre-commit hook completed"
exit 0